#!/usr/bin/env bash

machine_id="$1"
listen_ip="$2"

echo "starting riak on machine $machine_id, listen ip $listen_ip"
docker_host_ip=$(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}')
echo "docker host ip: $docker_host_ip"
etcdctl="etcdctl --peers http://$docker_host_ip:4001"

echo "storing current machine in etcd"
${etcdctl} set "/riak/bootstrap/machines/$machine_id" $listen_ip > /dev/null

echo "listing other bootstrap machines"
bootstrap_node_paths=( $(${etcdctl} ls /riak/bootstrap/machines) )
first_node_path=${bootstrap_node_paths[0]}

if [[ -n "${first_node_path}" ]]; then
  echo "getting node details $first_node_path"
  join_ip=$( ${etcdctl} get $first_node_path --consistent )
  echo "$first_node_path: $join_ip, current local ip: ${local_ip}"
  if [[ "${join_ip}" == "${local_ip}" ]]; then
    echo "starting as first node in cluster"
  else
    echo "starting new node in cluster, will join with ${join_ip}"
  fi
fi
