#!/usr/bin/env bash

listen_ip="$1"

docker_host_ip=$(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}')
echo "docker host ip: $docker_host_ip"
etcdctl="etcdctl --peers http://$docker_host_ip:4001"

echo "listing other riak machines"
bootstrap_node_paths=( $(${etcdctl} ls /riak/bootstrap/machines) )

if [ "${#selected_columns[@]}" -eq "1" ]; then
    echo "no other nodes available, can't join"
    exit 0
fi

for join_ip in $(${etcdctl} ls /riak/bootstrap/machines); do
  if [[ "${join_ip}" != "${listen_ip}" ]]; then
    echo "will join with ${join_ip}"
    /usr/sbin/riak-admin cluster join riak@${join_ip}
    /usr/sbin/riak-admin cluster plan
    /usr/sbin/riak-admin cluster commit
  fi
done
