#!/usr/bin/env bash

machine_id="$1"
listen_ip="$2"

chown riak:riak /data
chown riak:riak /logs

echo "starting riak on machine $machine_id, listen ip $listen_ip"
docker_host_ip=$(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}')
echo "docker host ip: $docker_host_ip"
etcdctl="etcdctl --peers http://$docker_host_ip:4001"

echo "storing current machine in etcd"
${etcdctl} set "/riak/bootstrap/machines/$machine_id" $listen_ip > /dev/null

echo "riak.conf: setting data directory to /data"
sed -i "s%/var/lib/riak%/data%" /etc/riak/riak.conf

echo "riak.conf: setting log directory to /logs"
sed -i 's%$(platform_log_dir)%/logs%' /etc/riak/riak.conf

echo "riak.conf: setting nodename = riak@${listen_ip}"
sed -i "s%nodename = riak@127.0.0.1%nodename = riak@${listen_ip}%" /etc/riak/riak.conf

echo "riak.conf: replacing 127.0.0.1 to 0.0.0.0"
sed -i "s%127.0.0.1%0.0.0.0%" /etc/riak/riak.conf

echo "starting riak via supervisord..."
/usr/bin/supervisord -c /etc/supervisord.conf
